### ISSUE TITLE
TODO : Maze Explorer

### ISSUE THREAD

**Issue by IkerZamora** [IkerZamora/erle_rover_explorer#1]
Similar to [ros_erle_pattern_follower](https://github.com/erlerobot/ros_erle_pattern_follower) control the Erle-Rover in manual mode. I'll be using the laser to avoid walls inside a maze.
- [x] Create the maze map model from a picture
- [x] Be able to subscribe to the laser topic
- [ ] Apply logic to obtain a throttle and yaw value from the laser readings
- [ ] Override the RC with those values and be able to walk through the maze without crashing the rover

**Comment by IkerZamora** [comment]
If overriding RC doesn't make any effect, `param show SYSID_MYGCS`

**Comment by IkerZamora** [comment]
RFF Algorithm
